import Head from 'next/head';
import Card from '../components/Card';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Hero from '../components/Hero';
import LargeCard from '../components/LargeCard';
import SmallCard from '../components/SmallCard';

export default function Home({ exploreData,cardsData }) {
  return (
    <div>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/airbnb_favicon.ico" />
      </Head>
       <Header />
       <Hero />
       <main className='max-w-7xl mx-auto px-8 sm:px-16'>
           <section className='pt-6'>
             <h2 className=' font-semibold  text-2xl md:text-3xl lg:text-4xl  pb-5'>Explore Nearby</h2>
             <div className='grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
               {exploreData?.map(({ img, location,distance}) =>(
                 <SmallCard key={img} img={img} location={location} distance={distance} />
               ))}
             </div>
           </section>
           <section>
           <h2 className=' font-semibold  text-2xl md:text-3xl lg:text-4xl  pb-5'>Live Anywhere</h2>
           <div className='flex space-x-4 overflow-scroll scrollbar-hide p-3'>
              {cardsData?.map(({img,title}) =>(
                <Card key={img} img={img} title={title} />
              ))}
           </div>
           </section>
           <LargeCard 
           img='https://links.papareact.com/4cj'
           title="The Greatest Outdoors"
           description="Wishlists created by Airbnb"
           buttonText="Get Inspired"
            />
       </main>
       <Footer />
    </div>
  )
}

export async function getStaticProps(){
  const exploreData = await  fetch('https://links.papareact.com/pyp').then(res => res.json());
  const cardsData = await  fetch('https://links.papareact.com/zp1').then(res => res.json());
   
    return{
      props:{
         exploreData,
         cardsData
      }
    }
}
